//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}declared_const_set_ref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}declared_type_set_ref" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}message_def"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}header"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}body"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}footer"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}array"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}record"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}list"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}variant"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}sequence"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}fixed_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}variable_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}bit_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}fixed_length_string"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}variable_length_string"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}variable_length_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}variable_format_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}value_set"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_message_def"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_event_def"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_header"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_body"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_footer"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_list"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_sequence"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_variant"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_record"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_array"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_fixed_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_variable_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_bit_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_fixed_length_string"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_variable_length_string"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_variable_length_field"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_variable_format_field"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{urn:jaus:jsidl:1.1}identifier" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="version" type="{urn:jaus:jsidl:1.1}version_num" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "declaredConstSetRef",
    "declaredTypeSetRef",
    "messageDefOrHeaderOrBody"
})
@XmlRootElement(name = "declared_type_set")
public class DeclaredTypeSet {

    @XmlElement(name = "declared_const_set_ref")
    protected java.util.List<DeclaredConstSetRef> declaredConstSetRef;
    @XmlElement(name = "declared_type_set_ref")
    protected java.util.List<DeclaredTypeSetRef> declaredTypeSetRef;
    @XmlElements({
        @XmlElement(name = "message_def", type = MessageDef.class),
        @XmlElement(name = "header", type = Header.class),
        @XmlElement(name = "body", type = Body.class),
        @XmlElement(name = "footer", type = Footer.class),
        @XmlElement(name = "array", type = Array.class),
        @XmlElement(name = "record", type = Record.class),
        @XmlElement(name = "list", type = org.jts.jsidl.binding.List.class),
        @XmlElement(name = "variant", type = Variant.class),
        @XmlElement(name = "sequence", type = Sequence.class),
        @XmlElement(name = "fixed_field", type = FixedField.class),
        @XmlElement(name = "variable_field", type = VariableField.class),
        @XmlElement(name = "bit_field", type = BitField.class),
        @XmlElement(name = "fixed_length_string", type = FixedLengthString.class),
        @XmlElement(name = "variable_length_string", type = VariableLengthString.class),
        @XmlElement(name = "variable_length_field", type = VariableLengthField.class),
        @XmlElement(name = "variable_format_field", type = VariableFormatField.class),
        @XmlElement(name = "value_set", type = ValueSet.class),
        @XmlElement(name = "declared_message_def", type = DeclaredMessageDef.class),
        @XmlElement(name = "declared_event_def", type = DeclaredEventDef.class),
        @XmlElement(name = "declared_header", type = DeclaredHeader.class),
        @XmlElement(name = "declared_body", type = DeclaredBody.class),
        @XmlElement(name = "declared_footer", type = DeclaredFooter.class),
        @XmlElement(name = "declared_list", type = DeclaredList.class),
        @XmlElement(name = "declared_sequence", type = DeclaredSequence.class),
        @XmlElement(name = "declared_variant", type = DeclaredVariant.class),
        @XmlElement(name = "declared_record", type = DeclaredRecord.class),
        @XmlElement(name = "declared_array", type = DeclaredArray.class),
        @XmlElement(name = "declared_fixed_field", type = DeclaredFixedField.class),
        @XmlElement(name = "declared_variable_field", type = DeclaredVariableField.class),
        @XmlElement(name = "declared_bit_field", type = DeclaredBitField.class),
        @XmlElement(name = "declared_fixed_length_string", type = DeclaredFixedLengthString.class),
        @XmlElement(name = "declared_variable_length_string", type = DeclaredVariableLengthString.class),
        @XmlElement(name = "declared_variable_length_field", type = DeclaredVariableLengthField.class),
        @XmlElement(name = "declared_variable_format_field", type = DeclaredVariableFormatField.class)
    })
    protected java.util.List<Object> messageDefOrHeaderOrBody;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the declaredConstSetRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the declaredConstSetRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeclaredConstSetRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeclaredConstSetRef }
     * 
     * 
     */
    public java.util.List<DeclaredConstSetRef> getDeclaredConstSetRef() {
        if (declaredConstSetRef == null) {
            declaredConstSetRef = new ArrayList<DeclaredConstSetRef>();
        }
        return this.declaredConstSetRef;
    }

    /**
     * Gets the value of the declaredTypeSetRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the declaredTypeSetRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeclaredTypeSetRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeclaredTypeSetRef }
     * 
     * 
     */
    public java.util.List<DeclaredTypeSetRef> getDeclaredTypeSetRef() {
        if (declaredTypeSetRef == null) {
            declaredTypeSetRef = new ArrayList<DeclaredTypeSetRef>();
        }
        return this.declaredTypeSetRef;
    }

    /**
     * Gets the value of the messageDefOrHeaderOrBody property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageDefOrHeaderOrBody property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageDefOrHeaderOrBody().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageDef }
     * {@link Header }
     * {@link Body }
     * {@link Footer }
     * {@link Array }
     * {@link Record }
     * {@link org.jts.jsidl.binding.List }
     * {@link Variant }
     * {@link Sequence }
     * {@link FixedField }
     * {@link VariableField }
     * {@link BitField }
     * {@link FixedLengthString }
     * {@link VariableLengthString }
     * {@link VariableLengthField }
     * {@link VariableFormatField }
     * {@link ValueSet }
     * {@link DeclaredMessageDef }
     * {@link DeclaredEventDef }
     * {@link DeclaredHeader }
     * {@link DeclaredBody }
     * {@link DeclaredFooter }
     * {@link DeclaredList }
     * {@link DeclaredSequence }
     * {@link DeclaredVariant }
     * {@link DeclaredRecord }
     * {@link DeclaredArray }
     * {@link DeclaredFixedField }
     * {@link DeclaredVariableField }
     * {@link DeclaredBitField }
     * {@link DeclaredFixedLengthString }
     * {@link DeclaredVariableLengthString }
     * {@link DeclaredVariableLengthField }
     * {@link DeclaredVariableFormatField }
     * 
     * 
     */
    public java.util.List<Object> getMessageDefOrHeaderOrBody() {
        if (messageDefOrHeaderOrBody == null) {
            messageDefOrHeaderOrBody = new ArrayList<Object>();
        }
        return this.messageDefOrHeaderOrBody;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
