//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}guard" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}internal"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}simple"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}push"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}pop"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}action"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}send_action"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{urn:jaus:jsidl:plus}mxCell" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="interpretation" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guard",
    "internal",
    "simple",
    "push",
    "pop",
    "actionOrSendAction",
    "mxCell"
})
@XmlRootElement(name = "default_transition")
public class DefaultTransition {

    protected Guard guard;
    protected Internal internal;
    protected Simple simple;
    protected Push push;
    protected Pop pop;
    @XmlElements({
        @XmlElement(name = "action", type = Action.class),
        @XmlElement(name = "send_action", type = SendAction.class)
    })
    protected List<Object> actionOrSendAction;
    @XmlElement(namespace = "urn:jaus:jsidl:plus")
    protected MxCell mxCell;
    @XmlAttribute(name = "interpretation")
    @XmlSchemaType(name = "anySimpleType")
    protected String interpretation;

    /**
     * Gets the value of the guard property.
     * 
     * @return
     *     possible object is
     *     {@link Guard }
     *     
     */
    public Guard getGuard() {
        return guard;
    }

    /**
     * Sets the value of the guard property.
     * 
     * @param value
     *     allowed object is
     *     {@link Guard }
     *     
     */
    public void setGuard(Guard value) {
        this.guard = value;
    }

    /**
     * Gets the value of the internal property.
     * 
     * @return
     *     possible object is
     *     {@link Internal }
     *     
     */
    public Internal getInternal() {
        return internal;
    }

    /**
     * Sets the value of the internal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Internal }
     *     
     */
    public void setInternal(Internal value) {
        this.internal = value;
    }

    /**
     * Gets the value of the simple property.
     * 
     * @return
     *     possible object is
     *     {@link Simple }
     *     
     */
    public Simple getSimple() {
        return simple;
    }

    /**
     * Sets the value of the simple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Simple }
     *     
     */
    public void setSimple(Simple value) {
        this.simple = value;
    }

    /**
     * Gets the value of the push property.
     * 
     * @return
     *     possible object is
     *     {@link Push }
     *     
     */
    public Push getPush() {
        return push;
    }

    /**
     * Sets the value of the push property.
     * 
     * @param value
     *     allowed object is
     *     {@link Push }
     *     
     */
    public void setPush(Push value) {
        this.push = value;
    }

    /**
     * Gets the value of the pop property.
     * 
     * @return
     *     possible object is
     *     {@link Pop }
     *     
     */
    public Pop getPop() {
        return pop;
    }

    /**
     * Sets the value of the pop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pop }
     *     
     */
    public void setPop(Pop value) {
        this.pop = value;
    }

    /**
     * Gets the value of the actionOrSendAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionOrSendAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionOrSendAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Action }
     * {@link SendAction }
     * 
     * 
     */
    public List<Object> getActionOrSendAction() {
        if (actionOrSendAction == null) {
            actionOrSendAction = new ArrayList<Object>();
        }
        return this.actionOrSendAction;
    }

    /**
     * Gets the value of the mxCell property.
     * 
     * @return
     *     possible object is
     *     {@link MxCell }
     *     
     */
    public MxCell getMxCell() {
        return mxCell;
    }

    /**
     * Sets the value of the mxCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link MxCell }
     *     
     */
    public void setMxCell(MxCell value) {
        this.mxCell = value;
    }

    /**
     * Gets the value of the interpretation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretation() {
        return interpretation;
    }

    /**
     * Sets the value of the interpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretation(String value) {
        this.interpretation = value;
    }

}
