//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}count_field"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}record"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_record"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}list"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_list"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}variant"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_variant"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}sequence"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_sequence"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{urn:jaus:jsidl:1.1}identifier" /&gt;
 *       &lt;attribute name="optional" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="interpretation" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "countField",
    "record",
    "declaredRecord",
    "list",
    "declaredList",
    "variant",
    "declaredVariant",
    "sequence",
    "declaredSequence"
})
@XmlRootElement(name = "list")
public class List {

    @XmlElement(name = "count_field", required = true)
    protected CountField countField;
    protected Record record;
    @XmlElement(name = "declared_record")
    protected DeclaredRecord declaredRecord;
    protected List list;
    @XmlElement(name = "declared_list")
    protected DeclaredList declaredList;
    protected Variant variant;
    @XmlElement(name = "declared_variant")
    protected DeclaredVariant declaredVariant;
    protected Sequence sequence;
    @XmlElement(name = "declared_sequence")
    protected DeclaredSequence declaredSequence;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "optional", required = true)
    protected boolean optional;
    @XmlAttribute(name = "interpretation")
    @XmlSchemaType(name = "anySimpleType")
    protected String interpretation;

    /**
     * Gets the value of the countField property.
     * 
     * @return
     *     possible object is
     *     {@link CountField }
     *     
     */
    public CountField getCountField() {
        return countField;
    }

    /**
     * Sets the value of the countField property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountField }
     *     
     */
    public void setCountField(CountField value) {
        this.countField = value;
    }

    /**
     * Gets the value of the record property.
     * 
     * @return
     *     possible object is
     *     {@link Record }
     *     
     */
    public Record getRecord() {
        return record;
    }

    /**
     * Sets the value of the record property.
     * 
     * @param value
     *     allowed object is
     *     {@link Record }
     *     
     */
    public void setRecord(Record value) {
        this.record = value;
    }

    /**
     * Gets the value of the declaredRecord property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredRecord }
     *     
     */
    public DeclaredRecord getDeclaredRecord() {
        return declaredRecord;
    }

    /**
     * Sets the value of the declaredRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredRecord }
     *     
     */
    public void setDeclaredRecord(DeclaredRecord value) {
        this.declaredRecord = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link List }
     *     
     */
    public List getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link List }
     *     
     */
    public void setList(List value) {
        this.list = value;
    }

    /**
     * Gets the value of the declaredList property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredList }
     *     
     */
    public DeclaredList getDeclaredList() {
        return declaredList;
    }

    /**
     * Sets the value of the declaredList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredList }
     *     
     */
    public void setDeclaredList(DeclaredList value) {
        this.declaredList = value;
    }

    /**
     * Gets the value of the variant property.
     * 
     * @return
     *     possible object is
     *     {@link Variant }
     *     
     */
    public Variant getVariant() {
        return variant;
    }

    /**
     * Sets the value of the variant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variant }
     *     
     */
    public void setVariant(Variant value) {
        this.variant = value;
    }

    /**
     * Gets the value of the declaredVariant property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredVariant }
     *     
     */
    public DeclaredVariant getDeclaredVariant() {
        return declaredVariant;
    }

    /**
     * Sets the value of the declaredVariant property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredVariant }
     *     
     */
    public void setDeclaredVariant(DeclaredVariant value) {
        this.declaredVariant = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link Sequence }
     *     
     */
    public Sequence getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sequence }
     *     
     */
    public void setSequence(Sequence value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the declaredSequence property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredSequence }
     *     
     */
    public DeclaredSequence getDeclaredSequence() {
        return declaredSequence;
    }

    /**
     * Sets the value of the declaredSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredSequence }
     *     
     */
    public void setDeclaredSequence(DeclaredSequence value) {
        this.declaredSequence = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the optional property.
     * 
     */
    public boolean isOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     * 
     */
    public void setOptional(boolean value) {
        this.optional = value;
    }

    /**
     * Gets the value of the interpretation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretation() {
        return interpretation;
    }

    /**
     * Sets the value of the interpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretation(String value) {
        this.interpretation = value;
    }

}
