//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}description"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}header"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_header"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}body"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_body"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}footer"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_footer"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{urn:jaus:jsidl:1.1}identifier" /&gt;
 *       &lt;attribute name="message_id" use="required" type="{http://www.w3.org/2001/XMLSchema}hexBinary" /&gt;
 *       &lt;attribute name="is_command" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="deprecated" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "header",
    "declaredHeader",
    "body",
    "declaredBody",
    "footer",
    "declaredFooter"
})
@XmlRootElement(name = "message_def")
public class MessageDef {

    @XmlElement(required = true)
    protected Description description;
    protected Header header;
    @XmlElement(name = "declared_header")
    protected DeclaredHeader declaredHeader;
    protected Body body;
    @XmlElement(name = "declared_body")
    protected DeclaredBody declaredBody;
    protected Footer footer;
    @XmlElement(name = "declared_footer")
    protected DeclaredFooter declaredFooter;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "message_id", required = true)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] messageId;
    @XmlAttribute(name = "is_command")
    protected Boolean isCommand;
    @XmlAttribute(name = "deprecated")
    protected Boolean deprecated;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the declaredHeader property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredHeader }
     *     
     */
    public DeclaredHeader getDeclaredHeader() {
        return declaredHeader;
    }

    /**
     * Sets the value of the declaredHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredHeader }
     *     
     */
    public void setDeclaredHeader(DeclaredHeader value) {
        this.declaredHeader = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link Body }
     *     
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link Body }
     *     
     */
    public void setBody(Body value) {
        this.body = value;
    }

    /**
     * Gets the value of the declaredBody property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredBody }
     *     
     */
    public DeclaredBody getDeclaredBody() {
        return declaredBody;
    }

    /**
     * Sets the value of the declaredBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredBody }
     *     
     */
    public void setDeclaredBody(DeclaredBody value) {
        this.declaredBody = value;
    }

    /**
     * Gets the value of the footer property.
     * 
     * @return
     *     possible object is
     *     {@link Footer }
     *     
     */
    public Footer getFooter() {
        return footer;
    }

    /**
     * Sets the value of the footer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Footer }
     *     
     */
    public void setFooter(Footer value) {
        this.footer = value;
    }

    /**
     * Gets the value of the declaredFooter property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredFooter }
     *     
     */
    public DeclaredFooter getDeclaredFooter() {
        return declaredFooter;
    }

    /**
     * Sets the value of the declaredFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredFooter }
     *     
     */
    public void setDeclaredFooter(DeclaredFooter value) {
        this.declaredFooter = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageId(byte[] value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the isCommand property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCommand() {
        return isCommand;
    }

    /**
     * Sets the value of the isCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCommand(Boolean value) {
        this.isCommand = value;
    }

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeprecated(Boolean value) {
        this.deprecated = value;
    }

}
