//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}input_set"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}output_set"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="interpretation" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputSet",
    "outputSet"
})
@XmlRootElement(name = "message_set")
public class MessageSet {

    @XmlElement(name = "input_set", required = true)
    protected InputSet inputSet;
    @XmlElement(name = "output_set", required = true)
    protected OutputSet outputSet;
    @XmlAttribute(name = "interpretation")
    @XmlSchemaType(name = "anySimpleType")
    protected String interpretation;

    /**
     * Gets the value of the inputSet property.
     * 
     * @return
     *     possible object is
     *     {@link InputSet }
     *     
     */
    public InputSet getInputSet() {
        return inputSet;
    }

    /**
     * Sets the value of the inputSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputSet }
     *     
     */
    public void setInputSet(InputSet value) {
        this.inputSet = value;
    }

    /**
     * Gets the value of the outputSet property.
     * 
     * @return
     *     possible object is
     *     {@link OutputSet }
     *     
     */
    public OutputSet getOutputSet() {
        return outputSet;
    }

    /**
     * Sets the value of the outputSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputSet }
     *     
     */
    public void setOutputSet(OutputSet value) {
        this.outputSet = value;
    }

    /**
     * Gets the value of the interpretation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretation() {
        return interpretation;
    }

    /**
     * Sets the value of the interpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretation(String value) {
        this.interpretation = value;
    }

}
