//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:jaus:jsidl:1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jts.jsidl.binding;
