//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="state" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{urn:jaus:jsidl:plus}mxCell"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="transition" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{urn:jaus:jsidl:plus}mxCell"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "state",
    "transition"
})
@XmlRootElement(name = "pseudo_start_state")
public class PseudoStartState {

    protected PseudoStartState.State state;
    protected PseudoStartState.Transition transition;

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link PseudoStartState.State }
     *     
     */
    public PseudoStartState.State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link PseudoStartState.State }
     *     
     */
    public void setState(PseudoStartState.State value) {
        this.state = value;
    }

    /**
     * Gets the value of the transition property.
     * 
     * @return
     *     possible object is
     *     {@link PseudoStartState.Transition }
     *     
     */
    public PseudoStartState.Transition getTransition() {
        return transition;
    }

    /**
     * Sets the value of the transition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PseudoStartState.Transition }
     *     
     */
    public void setTransition(PseudoStartState.Transition value) {
        this.transition = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{urn:jaus:jsidl:plus}mxCell"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mxCell"
    })
    public static class State {

        @XmlElement(namespace = "urn:jaus:jsidl:plus", required = true)
        protected MxCell mxCell;

        /**
         * Gets the value of the mxCell property.
         * 
         * @return
         *     possible object is
         *     {@link MxCell }
         *     
         */
        public MxCell getMxCell() {
            return mxCell;
        }

        /**
         * Sets the value of the mxCell property.
         * 
         * @param value
         *     allowed object is
         *     {@link MxCell }
         *     
         */
        public void setMxCell(MxCell value) {
            this.mxCell = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{urn:jaus:jsidl:plus}mxCell"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mxCell"
    })
    public static class Transition {

        @XmlElement(namespace = "urn:jaus:jsidl:plus", required = true)
        protected MxCell mxCell;

        /**
         * Gets the value of the mxCell property.
         * 
         * @return
         *     possible object is
         *     {@link MxCell }
         *     
         */
        public MxCell getMxCell() {
            return mxCell;
        }

        /**
         * Sets the value of the mxCell property.
         * 
         * @param value
         *     allowed object is
         *     {@link MxCell }
         *     
         */
        public void setMxCell(MxCell value) {
            this.mxCell = value;
        }

    }

}
