//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}inherits_from" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}client_of" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inheritsFrom",
    "clientOf"
})
@XmlRootElement(name = "references")
public class References {

    @XmlElement(name = "inherits_from")
    protected InheritsFrom inheritsFrom;
    @XmlElement(name = "client_of")
    protected List<ClientOf> clientOf;

    /**
     * Gets the value of the inheritsFrom property.
     * 
     * @return
     *     possible object is
     *     {@link InheritsFrom }
     *     
     */
    public InheritsFrom getInheritsFrom() {
        return inheritsFrom;
    }

    /**
     * Sets the value of the inheritsFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link InheritsFrom }
     *     
     */
    public void setInheritsFrom(InheritsFrom value) {
        this.inheritsFrom = value;
    }

    /**
     * Gets the value of the clientOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clientOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClientOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClientOf }
     * 
     * 
     */
    public List<ClientOf> getClientOf() {
        if (clientOf == null) {
            clientOf = new ArrayList<ClientOf>();
        }
        return this.clientOf;
    }

}
