//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}description"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}assumptions"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}references" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}declared_const_set" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}declared_type_set" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}message_set"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}internal_events_set"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}protocol_behavior"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{urn:jaus:jsidl:1.1}identifier" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="version" use="required" type="{urn:jaus:jsidl:1.1}version_num" /&gt;
 *       &lt;attribute name="deprecated" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "assumptions",
    "references",
    "declaredConstSet",
    "declaredTypeSet",
    "messageSet",
    "internalEventsSet",
    "protocolBehavior"
})
@XmlRootElement(name = "service_def")
public class ServiceDef {

    @XmlElement(required = true)
    protected Description description;
    @XmlElement(required = true)
    protected Assumptions assumptions;
    protected References references;
    @XmlElement(name = "declared_const_set")
    protected DeclaredConstSet declaredConstSet;
    @XmlElement(name = "declared_type_set")
    protected DeclaredTypeSet declaredTypeSet;
    @XmlElement(name = "message_set", required = true)
    protected MessageSet messageSet;
    @XmlElement(name = "internal_events_set", required = true)
    protected InternalEventsSet internalEventsSet;
    @XmlElement(name = "protocol_behavior", required = true)
    protected ProtocolBehavior protocolBehavior;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "deprecated")
    protected Boolean deprecated;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the assumptions property.
     * 
     * @return
     *     possible object is
     *     {@link Assumptions }
     *     
     */
    public Assumptions getAssumptions() {
        return assumptions;
    }

    /**
     * Sets the value of the assumptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assumptions }
     *     
     */
    public void setAssumptions(Assumptions value) {
        this.assumptions = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link References }
     *     
     */
    public References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link References }
     *     
     */
    public void setReferences(References value) {
        this.references = value;
    }

    /**
     * Gets the value of the declaredConstSet property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredConstSet }
     *     
     */
    public DeclaredConstSet getDeclaredConstSet() {
        return declaredConstSet;
    }

    /**
     * Sets the value of the declaredConstSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredConstSet }
     *     
     */
    public void setDeclaredConstSet(DeclaredConstSet value) {
        this.declaredConstSet = value;
    }

    /**
     * Gets the value of the declaredTypeSet property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredTypeSet }
     *     
     */
    public DeclaredTypeSet getDeclaredTypeSet() {
        return declaredTypeSet;
    }

    /**
     * Sets the value of the declaredTypeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredTypeSet }
     *     
     */
    public void setDeclaredTypeSet(DeclaredTypeSet value) {
        this.declaredTypeSet = value;
    }

    /**
     * Gets the value of the messageSet property.
     * 
     * @return
     *     possible object is
     *     {@link MessageSet }
     *     
     */
    public MessageSet getMessageSet() {
        return messageSet;
    }

    /**
     * Sets the value of the messageSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageSet }
     *     
     */
    public void setMessageSet(MessageSet value) {
        this.messageSet = value;
    }

    /**
     * Gets the value of the internalEventsSet property.
     * 
     * @return
     *     possible object is
     *     {@link InternalEventsSet }
     *     
     */
    public InternalEventsSet getInternalEventsSet() {
        return internalEventsSet;
    }

    /**
     * Sets the value of the internalEventsSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalEventsSet }
     *     
     */
    public void setInternalEventsSet(InternalEventsSet value) {
        this.internalEventsSet = value;
    }

    /**
     * Gets the value of the protocolBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolBehavior }
     *     
     */
    public ProtocolBehavior getProtocolBehavior() {
        return protocolBehavior;
    }

    /**
     * Sets the value of the protocolBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolBehavior }
     *     
     */
    public void setProtocolBehavior(ProtocolBehavior value) {
        this.protocolBehavior = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeprecated(Boolean value) {
        this.deprecated = value;
    }

}
