//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}entry" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}exit" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}transition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}default_transition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}state" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}default_state" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}pseudo_start_state" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:plus}mxCell" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{urn:jaus:jsidl:1.1}identifier_ns" /&gt;
 *       &lt;attribute name="initial_state" type="{urn:jaus:jsidl:1.1}identifier" /&gt;
 *       &lt;attribute name="interpretation" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entry",
    "exit",
    "transition",
    "defaultTransition",
    "state",
    "defaultState",
    "pseudoStartState",
    "mxCell"
})
@XmlRootElement(name = "state")
public class State {

    protected Entry entry;
    protected Exit exit;
    protected List<Transition> transition;
    @XmlElement(name = "default_transition")
    protected List<DefaultTransition> defaultTransition;
    protected List<State> state;
    @XmlElement(name = "default_state")
    protected DefaultState defaultState;
    @XmlElement(name = "pseudo_start_state")
    protected PseudoStartState pseudoStartState;
    @XmlElement(namespace = "urn:jaus:jsidl:plus")
    protected MxCell mxCell;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "initial_state")
    protected String initialState;
    @XmlAttribute(name = "interpretation")
    @XmlSchemaType(name = "anySimpleType")
    protected String interpretation;

    /**
     * Gets the value of the entry property.
     * 
     * @return
     *     possible object is
     *     {@link Entry }
     *     
     */
    public Entry getEntry() {
        return entry;
    }

    /**
     * Sets the value of the entry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entry }
     *     
     */
    public void setEntry(Entry value) {
        this.entry = value;
    }

    /**
     * Gets the value of the exit property.
     * 
     * @return
     *     possible object is
     *     {@link Exit }
     *     
     */
    public Exit getExit() {
        return exit;
    }

    /**
     * Sets the value of the exit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Exit }
     *     
     */
    public void setExit(Exit value) {
        this.exit = value;
    }

    /**
     * Gets the value of the transition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transition }
     * 
     * 
     */
    public List<Transition> getTransition() {
        if (transition == null) {
            transition = new ArrayList<Transition>();
        }
        return this.transition;
    }

    /**
     * Gets the value of the defaultTransition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultTransition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefaultTransition }
     * 
     * 
     */
    public List<DefaultTransition> getDefaultTransition() {
        if (defaultTransition == null) {
            defaultTransition = new ArrayList<DefaultTransition>();
        }
        return this.defaultTransition;
    }

    /**
     * Gets the value of the state property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the state property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link State }
     * 
     * 
     */
    public List<State> getState() {
        if (state == null) {
            state = new ArrayList<State>();
        }
        return this.state;
    }

    /**
     * Gets the value of the defaultState property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultState }
     *     
     */
    public DefaultState getDefaultState() {
        return defaultState;
    }

    /**
     * Sets the value of the defaultState property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultState }
     *     
     */
    public void setDefaultState(DefaultState value) {
        this.defaultState = value;
    }

    /**
     * Gets the value of the pseudoStartState property.
     * 
     * @return
     *     possible object is
     *     {@link PseudoStartState }
     *     
     */
    public PseudoStartState getPseudoStartState() {
        return pseudoStartState;
    }

    /**
     * Sets the value of the pseudoStartState property.
     * 
     * @param value
     *     allowed object is
     *     {@link PseudoStartState }
     *     
     */
    public void setPseudoStartState(PseudoStartState value) {
        this.pseudoStartState = value;
    }

    /**
     * Gets the value of the mxCell property.
     * 
     * @return
     *     possible object is
     *     {@link MxCell }
     *     
     */
    public MxCell getMxCell() {
        return mxCell;
    }

    /**
     * Sets the value of the mxCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link MxCell }
     *     
     */
    public void setMxCell(MxCell value) {
        this.mxCell = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the initialState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialState() {
        return initialState;
    }

    /**
     * Sets the value of the initialState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialState(String value) {
        this.initialState = value;
    }

    /**
     * Gets the value of the interpretation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretation() {
        return interpretation;
    }

    /**
     * Sets the value of the interpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretation(String value) {
        this.interpretation = value;
    }

}
