//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}bit_range"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}value_set"/&gt;
 *           &lt;element ref="{urn:jaus:jsidl:1.1}declared_value_set"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{urn:jaus:jsidl:1.1}identifier" /&gt;
 *       &lt;attribute name="interpretation" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bitRange",
    "valueSet",
    "declaredValueSet"
})
@XmlRootElement(name = "sub_field")
public class SubField {

    @XmlElement(name = "bit_range", required = true)
    protected BitRange bitRange;
    @XmlElement(name = "value_set")
    protected ValueSet valueSet;
    @XmlElement(name = "declared_value_set")
    protected DeclaredValueSet declaredValueSet;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "interpretation")
    @XmlSchemaType(name = "anySimpleType")
    protected String interpretation;

    /**
     * Gets the value of the bitRange property.
     * 
     * @return
     *     possible object is
     *     {@link BitRange }
     *     
     */
    public BitRange getBitRange() {
        return bitRange;
    }

    /**
     * Sets the value of the bitRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BitRange }
     *     
     */
    public void setBitRange(BitRange value) {
        this.bitRange = value;
    }

    /**
     * Gets the value of the valueSet property.
     * 
     * @return
     *     possible object is
     *     {@link ValueSet }
     *     
     */
    public ValueSet getValueSet() {
        return valueSet;
    }

    /**
     * Sets the value of the valueSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueSet }
     *     
     */
    public void setValueSet(ValueSet value) {
        this.valueSet = value;
    }

    /**
     * Gets the value of the declaredValueSet property.
     * 
     * @return
     *     possible object is
     *     {@link DeclaredValueSet }
     *     
     */
    public DeclaredValueSet getDeclaredValueSet() {
        return declaredValueSet;
    }

    /**
     * Sets the value of the declaredValueSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclaredValueSet }
     *     
     */
    public void setDeclaredValueSet(DeclaredValueSet value) {
        this.declaredValueSet = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the interpretation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretation() {
        return interpretation;
    }

    /**
     * Sets the value of the interpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretation(String value) {
        this.interpretation = value;
    }

}
