//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:48:03 AM UTC 
//


package org.jts.jsidl.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}value_range"/&gt;
 *         &lt;element ref="{urn:jaus:jsidl:1.1}value_enum"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="name" type="{urn:jaus:jsidl:1.1}identifier" /&gt;
 *       &lt;attribute name="offset_to_lower_limit" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valueRangeOrValueEnum"
})
@XmlRootElement(name = "value_set")
public class ValueSet {

    @XmlElements({
        @XmlElement(name = "value_range", type = ValueRange.class),
        @XmlElement(name = "value_enum", type = ValueEnum.class)
    })
    protected List<Object> valueRangeOrValueEnum;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "offset_to_lower_limit", required = true)
    protected boolean offsetToLowerLimit;

    /**
     * Gets the value of the valueRangeOrValueEnum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueRangeOrValueEnum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueRangeOrValueEnum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueRange }
     * {@link ValueEnum }
     * 
     * 
     */
    public List<Object> getValueRangeOrValueEnum() {
        if (valueRangeOrValueEnum == null) {
            valueRangeOrValueEnum = new ArrayList<Object>();
        }
        return this.valueRangeOrValueEnum;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the offsetToLowerLimit property.
     * 
     */
    public boolean isOffsetToLowerLimit() {
        return offsetToLowerLimit;
    }

    /**
     * Sets the value of the offsetToLowerLimit property.
     * 
     */
    public void setOffsetToLowerLimit(boolean value) {
        this.offsetToLowerLimit = value;
    }

}
